ad_presaison_professeur:
    resource: "@ADPresaisonBundle/Controller/ProfesseurController.php"
    type:     annotation

ad_presaison_inscriptionforfait:
    resource: "@ADPresaisonBundle/Controller/InscriptionforfaitController.php"
    type:     annotation

ad_presaison_danse:
    resource: "@ADPresaisonBundle/Controller/DanseController.php"
    type:     annotation

ad_presaison_adherent:
    resource: "@ADPresaisonBundle/Controller/AdherentController.php"
    type:     annotation

ad_presaison_courshebdomadaire:
    resource: "@ADPresaisonBundle/Controller/CourshebdomadaireController.php"
    type:     annotation

ad_presaison_salle:
    resource: "@ADPresaisonBundle/Controller/SalleController.php"
    type:     annotation

ad_presaison_lieu:
    resource: "@ADPresaisonBundle/Controller/LieuController.php"
    type:     annotation

ad_presaison:
    resource: "@ADPresaisonBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
